// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSdBxzMvN77jR4Q_ID1b51R2GpecwpKeU',
    appId: '1:280443091258:web:acc73d39b76b6844c17803',
    messagingSenderId: '280443091258',
    projectId: 'keuangan-app-2026-74ea7',
    authDomain: 'keuangan-app-2026-74ea7.firebaseapp.com',
    storageBucket: 'keuangan-app-2026-74ea7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGpjyJp--pcsEkVy-fbx9YhNnsR7tYA0s',
    appId: '1:280443091258:android:37be5378062dc5c6c17803',
    messagingSenderId: '280443091258',
    projectId: 'keuangan-app-2026-74ea7',
    storageBucket: 'keuangan-app-2026-74ea7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcYaTVqPjGtXT6gdZxnI-JnAWa5esgsOM',
    appId: '1:280443091258:ios:fd45588d45235e83c17803',
    messagingSenderId: '280443091258',
    projectId: 'keuangan-app-2026-74ea7',
    storageBucket: 'keuangan-app-2026-74ea7.firebasestorage.app',
    iosBundleId: 'com.example.manajemenKeuangan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcYaTVqPjGtXT6gdZxnI-JnAWa5esgsOM',
    appId: '1:280443091258:ios:fd45588d45235e83c17803',
    messagingSenderId: '280443091258',
    projectId: 'keuangan-app-2026-74ea7',
    storageBucket: 'keuangan-app-2026-74ea7.firebasestorage.app',
    iosBundleId: 'com.example.manajemenKeuangan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSdBxzMvN77jR4Q_ID1b51R2GpecwpKeU',
    appId: '1:280443091258:web:d97894fc94be4396c17803',
    messagingSenderId: '280443091258',
    projectId: 'keuangan-app-2026-74ea7',
    authDomain: 'keuangan-app-2026-74ea7.firebaseapp.com',
    storageBucket: 'keuangan-app-2026-74ea7.firebasestorage.app',
  );
}
